2025-02-01 21:08:26,169 - services.py - ERROR: Возникла ошибка module 'datetime' has no attribute 'strptime'
2025-02-01 21:08:26,624 - services.py - ERROR: Возникла ошибка module 'datetime' has no attribute 'strptime'
2025-02-01 21:08:26,718 - services.py - ERROR: Возникла ошибка module 'datetime' has no attribute 'strptime'
